android: PLATFORM=android SCREENSHOT_PATH=screenshots/android/ -r features/support -r features/android -r features/android/step_definitions --exclude features/ios -t @android

report: -f html -o reports/report.html

reportjson: -f json -o reports/report.json

android-report: -p android -f html -o reports/android-report.html

movetodo: MOVETODO=true

reset: RESET=true

tags: TAGS=true
